Simpler change to fix compatability with CustomJSONData
This replaces the more complicated fix in 81277f4ebc9324ac9d26653f4c6ecd5d767dcaf4.

Infinite mode wasn't working when the CustomJSONData plugin was installed.

When starting infinite mode, Infinite Beat Saber would call `BeatmapData.InsertBeatmapEventDataInOrder` which would lead to the exception:

```
KeyNotFoundException: The given key 'CustomJSONData.CustomBeatmap.CustomBPMChangeBeatmapEventData' was not present in the dictionary.
```

The problem was that CustomJSONData converted all of the map's `BeatmapDataItems` to its own `BeatmapDataItem` subclasses (e.g. `CustomBPMChangeBeatmapEventData`). Part of Beat Saber's `BeatmapData.InsertBeatmapEventDataInOrder` implementation blows up when given a `BeatmapDataItem` with which it isn't familiar.

The solution is to use CustomJSONData's `CustomBeatmapData` class instead of Beat Saber's `BeatmapData`. `CustomBeatmapData` knows how to deal with CustomJSONData's `BeatmapDataItem` subclasses.

`CustomBeatmapData` uses `CustomBeatmapDataSortedListForTypeAndIds`: https://github.com/Aeroluna/CustomJSONData/blob/b733cdee0906a71dcc017a391b8d4f5b1c634ee6/CustomJSONData/CustomBeatmap/CustomBeatmapData.cs#L28-L29

`CustomBeatmapDataSortedListForTypeAndIds` has special handling for inserting `BeatmapDataItems`: https://github.com/Aeroluna/CustomJSONData/blob/b733cdee0906a71dcc017a391b8d4f5b1c634ee6/CustomJSONData/CustomBeatmap/CustomBeatmapDataSortedListForTypes.cs#L21-L51